import { compileFromFile } from "json-schema-to-typescript";

import { readMetaManifest } from "./definitions.js";
import {
  compositionSchemaPath,
  generatedMetaTypesPath,
  generatedSchemaTypesPath,
  metaPath,
} from "./paths.js";
import {
  renderMetaTypes,
  renderSchemaTypePrelude,
  rewriteSchemaTypeReferences,
} from "./render.js";
import { writeGeneratedFile } from "./write.js";

const rawSchemaTypes = await compileFromFile(compositionSchemaPath, {
  bannerComment:
    "// Generated by tooling/generate-types from vendor/lumen-definitions/schemas/composition.schema.json.\n// Do not edit by hand.\n",
  cwd: compositionSchemaPath,
  declareExternallyReferenced: false,
  enableConstEnums: false,
  style: {
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
  },
  unreachableDefinitions: true,
});

const manifest = await readMetaManifest(metaPath);
const metaTypes = renderMetaTypes(manifest);
const schemaTypes = `${renderSchemaTypePrelude(manifest)}${rewriteSchemaTypeReferences(
  rawSchemaTypes,
  manifest,
)}`;

await Promise.all([
  writeGeneratedFile(generatedSchemaTypesPath, schemaTypes),
  writeGeneratedFile(generatedMetaTypesPath, metaTypes),
]);
