import type { MetaManifest, NodeSpec } from "./definitions.js";

const quote = (value: string): string => JSON.stringify(value);

const union = (values: readonly string[]): string =>
  values.length === 0 ? "never" : values.map(quote).join(" | ");

const uniqueSorted = (values: readonly string[]): string[] => [...new Set(values)].sort();

const typeNameForNode = (kind: string): string =>
  `${kind
    .split(/[^a-zA-Z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")}Node`;

const schemaTypeNameForNode = (kind: string): string =>
  `${typeNameForNode(kind).replace(/Node$/u, "")}SchemaNode`;

const propertyType = (kind: string): string => {
  switch (kind) {
    case "bool":
      return "boolean";
    case "color":
      return "Color";
    case "float":
    case "int":
      return "number";
    case "string":
      return "string";
    case "vec2":
      return "Vec2";
    default:
      return "NodeLiteralValue";
  }
};

const renderNodeInterface = (spec: NodeSpec): string => {
  const properties = spec.properties ?? [];
  const propertiesType =
    properties.length === 0
      ? "Readonly<Record<string, never>>"
      : `{\n${properties
          .map(
            (property) =>
              `    readonly ${quote(property.name)}?: ExpressionValue<${propertyType(
                property.kind,
              )}>;`,
          )
          .join("\n")}\n  }`;

  return `export interface ${typeNameForNode(spec.kind)} extends CompositionNodeBase<${quote(
    spec.kind,
  )}> {
  readonly properties?: ${propertiesType};
}`;
};

export function renderMetaTypes(manifest: MetaManifest): string {
  const nodeKinds = uniqueSorted(manifest.nodeKinds);
  const specs = Object.values(manifest.nodeSpecs);
  const categories = uniqueSorted(specs.map((spec) => spec.category));
  const portKinds = uniqueSorted(
    specs.flatMap((spec) => [
      ...(spec.inputs ?? []).map((port) => port.kind),
      ...(spec.outputs ?? []).map((port) => port.kind),
    ]),
  );
  const propertyKinds = uniqueSorted(
    specs.flatMap((spec) => (spec.properties ?? []).map((property) => property.kind)),
  );
  const nodeInterfaces = specs.map(renderNodeInterface).join("\n\n");
  const nodeUnion = specs.map((spec) => typeNameForNode(spec.kind)).join(" | ");

  return `// Generated by tooling/generate-types from vendor/lumen-definitions/definitions/meta.json.
// Do not edit by hand.

export type NodeCategory = ${union(categories)};
export type NodePortKind = ${union(portKinds)};
export type NodePropertyKind = ${union(propertyKinds)};
export type NodeKind = ${union(nodeKinds)};

export interface MetaManifest {
  readonly schemaVersion: ${JSON.stringify(manifest.schemaVersion)};
  readonly nodeKinds: readonly NodeKind[];
  readonly nodeSpecs: Readonly<Record<NodeKind, NodeSpec>>;
}

export interface NodeSpec {
  readonly kind: NodeKind;
  readonly label: string;
  readonly description: string;
  readonly category: NodeCategory;
  readonly inputs: readonly NodeInputPortSpec[];
  readonly outputs: readonly NodeOutputPortSpec[];
  readonly properties: readonly NodePropertySpec[];
  readonly defaultProperties: Readonly<Record<string, NodeLiteralValue>>;
}

export interface NodeInputPortSpec {
  readonly name: string;
  readonly kind: NodePortKind;
  readonly optional: boolean;
  readonly variadic: boolean;
}

export interface NodeOutputPortSpec {
  readonly name: string;
  readonly kind: NodePortKind;
}

export interface NodePropertySpec {
  readonly name: string;
  readonly kind: NodePropertyKind;
  readonly defaultValue: NodeLiteralValue;
  readonly metadata?: NodePropertyMetadata;
}

export interface NodePropertyMetadata {
  readonly enumOptions?: readonly NodeEnumOptionSpec[];
}

export interface NodeEnumOptionSpec {
  readonly label: string;
  readonly value: number | string;
}

export type NodeLiteralValue =
  | boolean
  | number
  | string
  | readonly [number, number]
  | readonly [number, number, number]
  | readonly [number, number, number, number]
  | readonly number[]
  | readonly string[];

export type ExpressionString = \`=\${string}\`;
export type ExpressionValue<T> = T | ExpressionString;
export type Vec2 = readonly [number, number];
export type Color =
  | readonly [number, number, number]
  | readonly [number, number, number, number]
  | \`#\${string}\`;

export interface CompositionNodeBase<TKind extends NodeKind> {
  readonly id: number;
  readonly type: TKind;
  readonly map?: Readonly<Record<string, readonly [number, number]>>;
}

${nodeInterfaces}

export type CompositionNode = ${nodeUnion};
`;
}

export function renderSchemaTypePrelude(manifest: MetaManifest): string {
  const specs = Object.values(manifest.nodeSpecs);
  const nodeAliases = specs
    .map((spec) => `${typeNameForNode(spec.kind)} as ${schemaTypeNameForNode(spec.kind)}`)
    .join(",\n  ");

  return `import type {
  Color,
  ${nodeAliases}
} from "./meta.js";

export interface Connection {
  readonly from_node: number;
  readonly from_port?: string;
  readonly to_node: number;
  readonly to_port: string;
}

`;
}

export function rewriteSchemaTypeReferences(schemaTypes: string, manifest: MetaManifest): string {
  return Object.values(manifest.nodeSpecs).reduce((content, spec) => {
    const originalName = schemaTypeNameForNode(spec.kind).replace(/SchemaNode$/u, "");
    const safeName = schemaTypeNameForNode(spec.kind);
    return content.replace(new RegExp(`\\b${originalName}\\b`, "gu"), safeName);
  }, schemaTypes);
}
