import type { MetaManifest, NodePropertySpec, NodeSpec } from "./definitions.js";

const quote = (value: string): string => JSON.stringify(value);

const union = (values: readonly string[]): string =>
  values.length === 0 ? "never" : values.map(quote).join(" | ");

const uniqueSorted = (values: readonly string[]): string[] => [...new Set(values)].sort();

const typeNameForNode = (kind: string): string =>
  `${kind
    .split(/[^a-zA-Z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")}Node`;

const typeNameForEnumProperty = (nodeKind: string, propertyName: string): string =>
  `${nodeKind
    .split(/[^a-zA-Z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")}${propertyName
    .split(/[^a-zA-Z0-9]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("")}`;

const enumTypeForProperty = (nodeKind: string, property: NodePropertySpec): string =>
  typeNameForEnumProperty(nodeKind, property.id);

const propertyType = (nodeKind: string, property: NodePropertySpec): string => {
  switch (property.kind) {
    case "bool":
      return "boolean";
    case "color":
      return "Color";
    case "float":
    case "int":
      return "number";
    case "string":
      return "string";
    case "vec2":
      return "Vec2";
    case "enum":
      return enumTypeForProperty(nodeKind, property);
    default:
      return "NodeLiteralValue";
  }
};

const renderEnumType = (spec: NodeSpec, property: NodePropertySpec): string =>
  `export type ${enumTypeForProperty(spec.kind, property)} = ${union(
    (property.enumOptions ?? []).map((option) => option.name),
  )};`;

const renderNodeInterface = (spec: NodeSpec): string => {
  const properties = spec.properties ?? [];
  const propertiesType =
    properties.length === 0
      ? "Readonly<Record<string, never>>"
      : `{\n${properties
          .map(
            (property) =>
              `    readonly ${quote(property.id)}?: ExpressionValue<${propertyType(
                spec.kind,
                property,
              )}>;`,
          )
          .join("\n")}\n  }`;

  return `export interface ${typeNameForNode(spec.kind)} extends CompositionNodeBase<${quote(
    spec.kind,
  )}> {
  readonly properties?: ${propertiesType};
}`;
};

const renderNodeMapMember = (spec: NodeSpec): string =>
  `  readonly ${quote(spec.kind)}: ${typeNameForNode(spec.kind)};`;

const renderNodeInputMapMember = (spec: NodeSpec): string =>
  `  readonly ${quote(spec.kind)}: Omit<${typeNameForNode(spec.kind)}, "id"> & {
    readonly id?: number;
  };`;

export function renderMetaTypes(manifest: MetaManifest): string {
  const nodeKinds = uniqueSorted(manifest.nodeKinds);
  const specs = Object.values(manifest.nodeSpecs);
  const categories = uniqueSorted(specs.map((spec) => spec.category));
  const portKinds = uniqueSorted(
    specs.flatMap((spec) => [
      ...(spec.inputs ?? []).map((port) => port.kind),
      ...(spec.outputs ?? []).map((port) => port.kind),
    ]),
  );
  const propertyKinds = uniqueSorted(
    specs.flatMap((spec) => (spec.properties ?? []).map((property) => property.kind)),
  );
  const enumTypes = specs
    .flatMap((spec) =>
      (spec.properties ?? [])
        .filter((property) => property.kind === "enum")
        .map((property) => renderEnumType(spec, property)),
    )
    .join("\n");
  const nodeInterfaces = specs.map(renderNodeInterface).join("\n\n");
  const nodeMap = specs.map(renderNodeMapMember).join("\n");
  const nodeInputMap = specs.map(renderNodeInputMapMember).join("\n");

  return `// Generated by tooling/generate-types from definitions/composition.schema.json.
// Do not edit by hand.

export type NodeCategory = ${union(categories)};
export type NodePortKind = ${union(portKinds)};
export type NodePropertyKind = ${union(propertyKinds)};
export type NodeKind = ${union(nodeKinds)};

export const schemaVersion = ${JSON.stringify(manifest.schemaVersion)} as const;

export interface MetaManifest {
  readonly schemaVersion: ${JSON.stringify(manifest.schemaVersion)};
  readonly nodeKinds: readonly NodeKind[];
  readonly nodeSpecs: Readonly<Record<NodeKind, NodeSpec>>;
}

export interface NodeSpec {
  readonly kind: NodeKind;
  readonly name: string;
  readonly description: string;
  readonly category: NodeCategory;
  readonly inputs: readonly NodeInputPortSpec[];
  readonly outputs: readonly NodeOutputPortSpec[];
  readonly properties: readonly NodePropertySpec[];
  readonly defaultProperties: Readonly<Record<string, NodeLiteralValue>>;
}

export interface NodeInputPortSpec {
  readonly name: string;
  readonly kind: NodePortKind;
  readonly optional: boolean;
  readonly variadic: boolean;
}

export interface NodeOutputPortSpec {
  readonly name: string;
  readonly kind: NodePortKind;
}

export interface NodePropertySpec {
  readonly id: string;
  readonly name: string;
  readonly kind: NodePropertyKind;
  readonly description: string;
  readonly defaultValue: NodeLiteralValue;
  readonly enumOptions?: readonly NodeEnumOptionSpec[];
  readonly constraints?: PropertyConstraintsSpec;
}

export interface PropertyConstraintsSpec {
  readonly min?: number;
  readonly max?: number;
  readonly step?: number;
  readonly format?: string;
  readonly multiline?: boolean;
  readonly recommendedRows?: number;
  readonly role?: string;
}

export interface NodeEnumOptionSpec {
  readonly name: string;
  readonly label: string;
  readonly value: number;
}

export type NodeLiteralValue =
  | boolean
  | number
  | string
  | readonly [number, number]
  | readonly [number, number, number]
  | readonly [number, number, number, number]
  | readonly number[]
  | readonly string[];

export type ExpressionString = \`=\${string}\`;
export type ExpressionValue<T> = T | ExpressionString;
export type Vec2 = readonly [number, number];
export type Color =
  | readonly [number, number, number]
  | readonly [number, number, number, number]
  | \`#\${string}\`;

${enumTypes}

export interface CompositionNodeBase<TKind extends NodeKind> {
  readonly id: number;
  readonly type: TKind;
  readonly map?: Readonly<Record<string, readonly [number, number]>>;
}

${nodeInterfaces}

export interface CompositionNodeByKind {
${nodeMap}
}

export interface CompositionNodeInputByKind {
${nodeInputMap}
}

export type CompositionNode<TKind extends NodeKind = NodeKind> = CompositionNodeByKind[TKind];
export type CompositionNodeInput<TKind extends NodeKind = NodeKind> = CompositionNodeInputByKind[TKind];
`;
}

export function renderSchemaTypePrelude(): string {
  return `import type {
  Color,
  CompositionNode
} from "./meta.js";

export interface Connection {
  readonly from_node: number;
  readonly from_port?: string;
  readonly to_node: number;
  readonly to_port: string;
}

`;
}

export function renderCompositionTypes(): string {
  return `// Generated by tooling/generate-types from definitions/composition.schema.json.
// Do not edit by hand.

export interface LumenComposition {
  readonly $schema?: string;
  readonly audio?: {
    readonly clips: readonly {
      readonly duration_frames?: number;
      readonly duration_ms?: number;
      readonly id: string;
      readonly name?: string;
      readonly source_id: string;
      readonly source_start_ms?: number;
      readonly source_start_seconds?: number;
      readonly start_frame?: number;
      readonly start_ms?: number;
      readonly track_id: string;
      readonly volume?: number;
      readonly [key: string]: unknown;
    }[];
    readonly tracks: readonly {
      readonly id: string;
      readonly muted?: boolean;
      readonly name?: string;
      readonly solo?: boolean;
      readonly volume?: number;
      readonly [key: string]: unknown;
    }[];
    readonly [key: string]: unknown;
  };
  readonly connections: readonly Connection[];
  readonly lumenSchemaVersion?: string;
  readonly metadata?: {
    readonly name?: string;
    readonly [key: string]: unknown;
  };
  readonly nodes: readonly CompositionNode[];
  readonly render_settings: {
    readonly background_color?: Color;
    readonly height: number;
    readonly width: number;
  };
  readonly schemaVersion?: string;
  readonly timeline: {
    readonly duration_frames: number;
    readonly fps: number;
  };
  readonly [key: string]: unknown;
}
`;
}

export function rewriteSchemaTypeReferences(schemaTypes: string, manifest: MetaManifest): string {
  return Object.values(manifest.nodeSpecs).reduce((content, spec) => {
    const originalName = typeNameForNode(spec.kind).replace(/Node$/u, "");
    return content.replace(new RegExp(`\\b${originalName}\\b`, "gu"), typeNameForNode(spec.kind));
  }, schemaTypes);
}
