[package]
name = "lumen"
version = "0.1.0"
edition = "2024"

[lib]
name = "lumen"
path = "src/lib.rs"

[features]
default = ["renderer-skia"]
renderer-skia = ["dep:skia-safe"]
skia-metal = ["renderer-skia"]
skia-vulkan = ["renderer-skia"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg", "webp"] }
taffy = "0.9.2"
rayon = "1.11.0"

# Skia renderer deps
skia-safe = { version = "0.91", optional = true, features = ["textlayout"] }

[dev-dependencies]
serde_json = "1.0.149"
