apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lumen
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: us-east1-docker.pkg.dev/clipit-446800/lumiscia/lumen
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "12Gi"
              cpu: "4"
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: lumen-secret
                  key: SECRET
      containerConcurrency: 4
  traffic:
    - latestRevision: true
      percent: 100
