[package]
name = "lumen-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["json", "embed-roboto"]
json = ["lumen/json"]
embed-roboto = ["lumen/embed-roboto"]

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "CanvasRenderingContext2d",
  "ImageData",
  "OffscreenCanvas",
  "OffscreenCanvasRenderingContext2d",
  "VideoFrame",
  "WebGl2RenderingContext",
] }

lumen = { path = "../lumen", features = ["webgl"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
