[package]
name = "lumen-local"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lumen-local"
path = "src/main.rs"

[features]
default = []
cuda = ["lumen/cuda", "lumen-ffmpeg/cuda"]
metal = ["dep:objc2", "dep:objc2-metal", "lumen/metal", "lumen-ffmpeg/metal", "lumen-gpu/metal"]
vulkan = ["lumen/vulkan", "lumen-gpu/vulkan", "lumen-ffmpeg/vulkan"]


[dependencies]
anyhow = "1.0.101"
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg", "webp"] }
tempfile = "3.23.0"
lumen = { path = "../lumen", features = ["ffmpeg", "image", "json"] }
lumen-gpu = { path = "../lumen-gpu" }
lumen-ffmpeg = { version = "0.1.0", path = "../lumen-ffmpeg", features = ["vulkan"] }
objc2 = { version = "0.6.4", optional = true }
objc2-metal = { version = "0.3.2", optional = true }
pollster = "0.4.0"
serde_json = "1.0.145"
